### ISSUE TITLE
Something wrong with CORS in v2.5?

### ISSUE THREAD

**Issue by crittlc** [DVBproject/DVB-I-Reference-Client#20] opened 2020-04-21 15:19 UTC
Maybe it's on my side, however in [http://stage.sofiadigital.fi/dvb/dvb-i-reference-application/frontend/android/player.html](http://stage.sofiadigital.fi/dvb/dvb-i-reference-application/frontend/android/player.htm) when pressing "Filter" I just get a CORS error in the console trying to open [https://devel.sofiadigital.fi/home/tsa/dvb-i-reference-application/backend/servicelist_registry.php](https://devel.sofiadigital.fi/home/tsa/dvb-i-reference-application/backend/servicelist_registry.php).

Cloning it on a local server, while trying to open [https://10.54.131.203/dash/dvbi/DVB-I-Reference-Client-master/backend/servicelist_registry.php] I just get an "HTTP Error 500".

Any clue?

**Comment by paulhiggs** [comment] 2020-04-21 20:14
I seem to have some similar issue. Menu items not showing up on Android
![Screenshot_20200421_211257](https://user-images.githubusercontent.com/3158807/79909583-23eaee00-8415-11ea-94d1-6d172c74e0cd.jpg)

**Comment by juhajoki** [comment] 2020-04-22 04:19
looks like there's a development server leftover in the public release. We'll fix this asap.

**Comment by sofia-tsa** [comment] 2020-04-22 07:36
Development URL for the provider list was accidentally committed, fixed in a08c210b107b607087d121c40fc38f287b0608b8
The button issue was caused by a failure in selecting the default language, fixed in 6bacb458636d38b1d4bbb3f75def2991d2c31b8c

**Comment by crittlc** [comment] 2020-04-22 07:59
It works  now, thanks.

Would it be possible to replace PROVIDER_LIST with a relative URL instead of absolute?
It would allow a local deployment (without the need of manually updating dvbi-common.js)

**Comment by sofia-tsa** [comment] 2020-04-22 08:18
Should be possible. The reason for the absolute url was that the relative URL isn't the same for HbbTV and Android clients because of the different directory structure. But it should be possible to determine the path of the dvbi-common.js and using that as the base for the relative provider lisrt URL.

**Comment by paulhiggs** [comment] 2020-04-22 09:13
Alternatvely, we could just have a config.js file that contains configurable items for local installations, with some comments about what these configurable items are for

**Comment by paulhiggs** [comment] 2020-04-28 09:43
> I seem to have some similar issue. Menu items not showing up on Android
> ![Screenshot_20200421_211257](https://user-images.githubusercontent.com/3158807/79909583-23eaee00-8415-11ea-94d1-6d172c74e0cd.jpg)

This is ow fixed!

**Comment by sofia-tsa** [comment] 2020-08-05 12:28
Issue fixed. If the provider list URL needs to be changed to a relative URL, please make a new issue.

**Closed by sofia-tsa** 2020-08-05 12:28 UTC
